### PR TITLE
Fix bot since travis migration

### LINKED ISSUE #12: Enable the bot to work with travis-ci.com (pro?)
Currently, the bot seems to be working with travis-ci.org only. Allowing it to use travis-ci.com would make it more generic.

### PR DESCRIPTION
**Pull request by keneanung**
This PR contains the following changes:
- fetch the translation stats from appveyor instead of Travis
- use https://make.mudlet.org/snapshots/ to retrieve the links to test versions
- avoid the Travis API completely

This fixes #12

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -91,85 +53,102 @@ const updateDeploymentCommentBody = async (repoOwner, repoName, comment, github)
...
-  await github.issues.createComment({
-    owner: payload.repository.owner.login,
-    repo: payload.repository.name,
-    number: payload.number,
-    body: body
-  })
+  return platform
+}
+
+const scrapeMudletSnapshotsForLinks = async prNumber => {
```
Comment (vadi2) [inline index.js]: Perhaps not scrape anymore?

Comment (keneanung) [reply index.js]: Argh, right. I knew I forgot something... The version here is already running, but I'll fix it ASAP, but I don't know if I get to it before the vacation.
